package io.quarkiverse.grpc.spi;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class SpiExtensionTest {

    @Test
    public void testSpiGenerator() throws IOException {
        // The file should be generated in target/generated-sources/grpc
        Path generatedFile = Paths.get("target", "generated-sources", "grpc", "io", "quarkiverse", "grpc", "spi",
                "GeneratedBySpi.txt");
        assertThat(generatedFile).exists();
        assertThat(Files.readString(generatedFile)).contains("This file was generated by a custom SPI Generator");
    }

    @Test
    public void testSpiPostProcessor() throws IOException {
        // Check if one of the generated java files is signed
        Path generatedJavaFile = Paths.get("target", "generated-sources", "grpc", "io", "quarkiverse", "grpc", "spi",
                "SpiRequest.java");
        assertThat(generatedJavaFile).exists();
        assertThat(Files.readString(generatedJavaFile)).contains("// Signed by TestPostProcessor");
    }
}
