package io.quarkiverse.grpc.spi;

import java.util.stream.Stream;

import com.google.protobuf.compiler.PluginProtos;

import io.quarkiverse.grpc.codegen.GrpcZeroGenerator;

public class TestGenerator implements GrpcZeroGenerator {
    @Override
    public Stream<PluginProtos.CodeGeneratorResponse.File> generate(PluginProtos.CodeGeneratorRequest request) {
        return Stream.of(PluginProtos.CodeGeneratorResponse.File.newBuilder()
                .setName("io/quarkiverse/grpc/spi/GeneratedBySpi.txt")
                .setContent("This file was generated by a custom SPI Generator")
                .build());
    }
}
